spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5422/tennis-score
  sql:
    init:
      mode: always
  security:
    user:
      name: tennisscore
      password: e6c7cdca-0eca-48b7-afcb-79a32f166229
